import {env} from 'cloudflare:workers';
import {NextRequest,NextResponse} from 'next/server';
import {teacherIdentity} from '../../server-auth';
const db=()=>env.DB!;
const ok=(data:unknown,status=200)=>NextResponse.json(data,{status,headers:{'Cache-Control':'no-store'}});
const err=(message:string,status=400)=>ok({error:message},status);
const id=()=>crypto.randomUUID();
const now=()=>Date.now();
const code=()=>Array.from(crypto.getRandomValues(new Uint8Array(5)),x=>'ABCDEFGHJKLMNPQRSTUVWXYZ23456789'[x%32]).join('');
const query=(sql:string,...args:any[])=>db().prepare(sql).bind(...args);
const ROOM='SELECT * FROM sessions WHERE code=?';
async function room(c:string){return query(ROOM,c.trim().toUpperCase()).first<any>()}
async function actor(s:any,token:string,req:NextRequest){if(token&&token===s.teacher_token&&(!s.owner_user_id||s.owner_user_id===(await teacherIdentity(req))))return {role:'teacher',id:null,name:'先生',team:null,xp:0,avatar:'🎓'};const p=await query('SELECT id,name,team,xp,avatar FROM participants WHERE session_id=? AND token=?',s.id,token).first<any>();return p?{role:'student',...p}:null}
function insight(posts:any[],participants:any[],reactions:any[],responders:any[]){const questions=posts.filter(p=>p.kind==='question');const unsure=reactions.filter(r=>r.emoji==='🤔').length;const unique=new Set([...posts.map(p=>p.participant_id),...reactions.map(r=>r.participant_id),...responders.map(r=>r.participant_id)]).size;return {unique,participation:participants.length?Math.round(unique/participants.length*100):0,questions:questions.length,unsure,tip:unsure>=3?'🤔が増えています。理解度を確かめる投票を入れてみましょう。':questions.length>=3?'質問が集まっています。注目の問いをスクリーンに表示してみましょう。':'一言のリアクションから参加を促しましょう。'} }
export async function GET(req:NextRequest){try{if(req.nextUrl.searchParams.get('scope')==='mine'){const owner=await teacherIdentity(req);if(!owner)return err('先生の認証が必要です',401);const rows=await query('SELECT code,title,status,teacher_token AS token,created_at AS createdAt FROM sessions WHERE owner_user_id=? ORDER BY created_at DESC LIMIT 100',owner).all();return ok({sessions:rows.results})}const s=await room(req.nextUrl.searchParams.get('code')||'');if(!s)return err('ルームが見つかりません',404);const a=await actor(s,req.headers.get('x-room-token')||'',req);if(!a)return err('参加し直してください',401);const [people,postRows,act,res,react,ref,responders,reports]=await Promise.all([
query('SELECT id,name,avatar,team,xp FROM participants WHERE session_id=? ORDER BY joined_at',s.id).all<any>(),
query('SELECT p.*,u.name,u.avatar,u.team FROM posts p JOIN participants u ON u.id=p.participant_id WHERE p.session_id=? AND p.hidden=0 ORDER BY p.pinned DESC,p.created_at DESC LIMIT 100',s.id).all<any>(),
s.activity_id?query('SELECT * FROM activities WHERE id=?',s.activity_id).first<any>():null,
s.activity_id?query('SELECT participant_id,option_index FROM responses WHERE activity_id=?',s.activity_id).all<any>():null,
query('SELECT participant_id,emoji,created_at FROM reactions WHERE session_id=? AND created_at>? ORDER BY created_at DESC LIMIT 100',s.id,now()-60000).all<any>(),
a.role==='student'?query('SELECT takeaway,changed FROM reflections WHERE session_id=? AND participant_id=? ORDER BY created_at DESC LIMIT 1',s.id,a.id).first<any>():null,
query('SELECT DISTINCT r.participant_id FROM responses r JOIN activities a ON a.id=r.activity_id WHERE a.session_id=?',s.id).all<any>(),
a.role==='teacher'?query('SELECT reports.post_id,posts.body,count(*) AS n FROM reports JOIN posts ON posts.id=reports.post_id WHERE reports.session_id=? GROUP BY reports.post_id,posts.body',s.id).all<any>():null]);
const participants=people.results,allPosts=postRows.results,reactions=react.results;const visible=allPosts.map(p=>({...p,name:a.role==='teacher'||s.anonymous_mode==='real'?p.name:s.anonymous_mode==='all'?'匿名':p.participant_id===a.id?p.name:'匿名',participant_id:undefined}));const answers=res?.results||[];const activity=act?{id:act.id,kind:act.kind,prompt:act.prompt,options:JSON.parse(act.options),answer:a.role==='teacher'||s.status==='ended'?act.answer:null,endsAt:act.ends_at,counts:JSON.parse(act.options).map((_:string,i:number)=>answers.filter(r=>r.option_index===i).length),myAnswer:answers.find(r=>r.participant_id===a.id)?.option_index??null}:null;
const metrics=insight(allPosts,participants,reactions,responders.results);const teamScores=Object.fromEntries(['FIRE','AQUA','FOREST','VOLT'].map(t=>[t,participants.filter(p=>p.team===t).reduce((v,p)=>v+p.xp,0)]));const badges=a.role==='student'?[...(a.xp>=10?['はじめの一歩']:[]),...(allPosts.some(p=>p.participant_id===a.id&&p.kind==='question')?['勇気の質問']:[]),...(a.xp>=100?['探究者']:[])]:[];
return ok({room:{title:s.title,code:s.code,status:s.status,anonymousMode:s.anonymous_mode,screenMode:s.screen_mode},role:a.role,me:a,participants:a.role==='teacher'?participants:participants.map(p=>({avatar:p.avatar,team:p.team})),posts:visible,activity,reactions:reactions.map(r=>({emoji:r.emoji,createdAt:r.created_at})),metrics,teamScores,badges,reflection:ref,reports:reports?.results||[]});}catch(e){console.error(e);return err('読み込みに失敗しました',500)}}
export async function POST(req:NextRequest){try{const b:any=await req.json();if(b.action==='create'){const owner=await teacherIdentity(req);if(!owner)return err('先生はサインインするか、管理用コードを入力してください',401);const title=String(b.title||'今日の授業').trim().slice(0,80);let c=code();for(let i=0;i<8&&await room(c);i++)c=code();const token=id()+id();await query('INSERT INTO sessions(id,title,code,teacher_token,owner_user_id,status,created_at) VALUES(?,?,?,?,?,?,?)',id(),title,c,token,owner,'live',now()).run();return ok({code:c,token})}const s=await room(String(b.code||''));if(!s)return err('ルームが見つかりません',404);
if(b.action==='join'){if(s.status!=='live')return err('この授業は終了しました');const name=String(b.name||'').trim().slice(0,24);if(!name)return err('ニックネームを入力してください');const avatars=['🦊','🐻','🐼','🐱','🐸','🐧','🦁','🐨'];const avatar=avatars.includes(b.avatar)?b.avatar:'🦊';const count=await query('SELECT count(*) n FROM participants WHERE session_id=?',s.id).first<any>();const team=['FIRE','AQUA','FOREST','VOLT'][count.n%4];const token=id()+id();await query('INSERT INTO participants(id,session_id,name,avatar,team,token,joined_at) VALUES(?,?,?,?,?,?,?)',id(),s.id,name,avatar,team,token,now()).run();return ok({code:s.code,token})}
const a=await actor(s,req.headers.get('x-room-token')||'',req);if(!a)return err('操作する権限がありません',403);
if(b.action==='reaction'&&a.role==='student'&&s.status==='live'){if(!['😀','❤️','💡','🔥','🤔','👏'].includes(b.emoji))return err('リアクションを選んでください');const recent=await query('SELECT created_at FROM reactions WHERE participant_id=? ORDER BY created_at DESC LIMIT 1',a.id).first<any>();if(recent&&now()-recent.created_at<1500)return err('少し待ってから押してください');await db().batch([query('INSERT INTO reactions(id,session_id,participant_id,emoji,created_at) VALUES(?,?,?,?,?)',id(),s.id,a.id,b.emoji,now()),query('UPDATE participants SET xp=xp+2 WHERE id=?',a.id)]);return ok({ok:true})}
if(b.action==='post'&&a.role==='student'&&s.status==='live'){const body=String(b.body||'').trim().slice(0,400),kind=['question','idea','comment'].includes(b.kind)?b.kind:'comment';if(!body)return err('内容を入力してください');if(/https?:\/\//i.test(body))return err('リンクは投稿できません');if(/(?:死ね|殺す|ばかやろう)/.test(body))return err('表現を見直してから投稿してください');const recent=await query('SELECT created_at FROM posts WHERE participant_id=? ORDER BY created_at DESC LIMIT 1',a.id).first<any>();if(recent&&now()-recent.created_at<5000)return err('少し待ってから投稿してください');await db().batch([query('INSERT INTO posts(id,session_id,participant_id,kind,body,created_at) VALUES(?,?,?,?,?,?)',id(),s.id,a.id,kind,body,now()),query('UPDATE participants SET xp=xp+? WHERE id=?',kind==='question'?20:12,a.id)]);return ok({ok:true})}
if(b.action==='like'&&a.role==='student'&&s.status==='live'){const post=await query('SELECT id FROM posts WHERE id=? AND session_id=? AND hidden=0',b.postId,s.id).first();if(!post)return err('投稿が見つかりません');const prior=await query('SELECT rowid FROM likes WHERE post_id=? AND participant_id=?',b.postId,a.id).first();if(prior)return err('共感済みです');await db().batch([query('INSERT INTO likes(post_id,participant_id) VALUES(?,?)',b.postId,a.id),query('UPDATE posts SET likes=likes+1 WHERE id=?',b.postId)]);return ok({ok:true})}
if(b.action==='report'&&a.role==='student'){const post=await query('SELECT id FROM posts WHERE id=? AND session_id=? AND hidden=0',b.postId,s.id).first();if(!post)return err('投稿が見つかりません');const prior=await query('SELECT id FROM reports WHERE post_id=? AND participant_id=?',b.postId,a.id).first();if(prior)return err('通報済みです');await query('INSERT INTO reports(id,session_id,post_id,participant_id,created_at) VALUES(?,?,?,?,?)',id(),s.id,b.postId,a.id,now()).run();return ok({ok:true})}
if(b.action==='answer'&&a.role==='student'&&s.status==='live'&&s.activity_id){const act=await query('SELECT * FROM activities WHERE id=?',s.activity_id).first<any>();const n=Number(b.index);if(act.ends_at&&now()>act.ends_at)return err('回答時間が終了しました');if(!Number.isInteger(n)||n<0||n>=JSON.parse(act.options).length)return err('回答を選んでください');const prior=await query('SELECT id FROM responses WHERE participant_id=? AND activity_id=?',a.id,act.id).first();if(prior)return err('回答済みです');const xp=act.kind==='quiz'?(n===act.answer?30:10):10;await db().batch([query('INSERT INTO responses(id,activity_id,participant_id,option_index,created_at) VALUES(?,?,?,?,?)',id(),act.id,a.id,n,now()),query('UPDATE participants SET xp=xp+? WHERE id=?',xp,a.id)]);return ok({ok:true})}
if(b.action==='reflect'&&a.role==='student'&&s.status==='ended'){const takeaway=String(b.takeaway||'').trim().slice(0,300),changed=String(b.changed||'').trim().slice(0,300);if(!takeaway)return err('今日の学びをひとこと書いてください');const prior=await query('SELECT id FROM reflections WHERE session_id=? AND participant_id=?',s.id,a.id).first();if(prior)return err('振り返りは保存済みです');await db().batch([query('INSERT INTO reflections(id,session_id,participant_id,takeaway,changed,created_at) VALUES(?,?,?,?,?,?)',id(),s.id,a.id,takeaway,changed,now()),query('UPDATE participants SET xp=xp+25 WHERE id=?',a.id)]);return ok({ok:true})}
if(a.role==='teacher'){if(b.action==='activity'&&s.status==='live'){const kinds=['quiz','poll','mission'];const kind=kinds.includes(b.kind)?b.kind:'poll',prompt=String(b.prompt||'').trim().slice(0,200),options=kind==='mission'?['できた','考え中']:Array.isArray(b.options)?b.options.map((x:unknown)=>String(x).trim().slice(0,80)).filter(Boolean).slice(0,4):[];if(!prompt||options.length<2)return err('問いと選択肢を2つ以上入力してください');const answer=kind==='quiz'?Number(b.answer):null;if(kind==='quiz'&&(answer===null||!Number.isInteger(answer)||answer<0||answer>=options.length))return err('正解を選んでください');const aid=id(),endsAt=b.timer?now()+30000:null;await db().batch([query('INSERT INTO activities(id,session_id,kind,prompt,options,answer,ends_at,created_at) VALUES(?,?,?,?,?,?,?,?)',aid,s.id,kind,prompt,JSON.stringify(options),answer,endsAt,now()),query('UPDATE sessions SET activity_id=? WHERE id=?',aid,s.id)]);return ok({ok:true})}
if(b.action==='hide'||b.action==='pin'){await query(`UPDATE posts SET ${b.action==='hide'?'hidden=1':'pinned=1-pinned'} WHERE id=? AND session_id=?`,b.postId,s.id).run();return ok({ok:true})}
if(b.action==='settings'){const anonymous=['all','peers','real'].includes(b.anonymousMode)?b.anonymousMode:s.anonymous_mode;const screen=['overview','question','activity','teams'].includes(b.screenMode)?b.screenMode:s.screen_mode;await query('UPDATE sessions SET anonymous_mode=?,screen_mode=? WHERE id=?',anonymous,screen,s.id).run();return ok({ok:true})}
if(b.action==='end'){await query("UPDATE sessions SET status='ended' WHERE id=?",s.id).run();return ok({ok:true})}}
return err('この操作はできません',403)}catch(e){console.error(e);return err('保存に失敗しました',500)}}
