import { sqliteTable, text, integer, index, uniqueIndex } from 'drizzle-orm/sqlite-core';
export const sessions = sqliteTable('sessions', { id:text('id').primaryKey(), title:text('title').notNull(), code:text('code').notNull().unique(), teacherToken:text('teacher_token').notNull(), ownerUserId:text('owner_user_id'), status:text('status').notNull().default('live'), activityId:text('activity_id'), anonymousMode:text('anonymous_mode').notNull().default('peers'), screenMode:text('screen_mode').notNull().default('overview'), createdAt:integer('created_at').notNull() });
export const participants = sqliteTable('participants', { id:text('id').primaryKey(), sessionId:text('session_id').notNull().references(()=>sessions.id), name:text('name').notNull(), avatar:text('avatar').notNull().default('🦊'), team:text('team').notNull().default('FIRE'), xp:integer('xp').notNull().default(0), token:text('token').notNull().unique(), joinedAt:integer('joined_at').notNull() }, t=>[index('idx_participants_session').on(t.sessionId)]);
export const posts = sqliteTable('posts', { id:text('id').primaryKey(), sessionId:text('session_id').notNull().references(()=>sessions.id), participantId:text('participant_id').notNull().references(()=>participants.id), kind:text('kind').notNull(), body:text('body').notNull(), hidden:integer('hidden').notNull().default(0), likes:integer('likes').notNull().default(0), pinned:integer('pinned').notNull().default(0), createdAt:integer('created_at').notNull() }, t=>[index('idx_posts_session_created').on(t.sessionId,t.createdAt)]);
export const activities = sqliteTable('activities', { id:text('id').primaryKey(), sessionId:text('session_id').notNull().references(()=>sessions.id), kind:text('kind').notNull(), prompt:text('prompt').notNull(), options:text('options').notNull(), answer:integer('answer'), endsAt:integer('ends_at'), createdAt:integer('created_at').notNull() }, t=>[index('idx_activities_session').on(t.sessionId)]);
export const responses = sqliteTable('responses', { id:text('id').primaryKey(), activityId:text('activity_id').notNull().references(()=>activities.id), participantId:text('participant_id').notNull().references(()=>participants.id), optionIndex:integer('option_index').notNull(), createdAt:integer('created_at').notNull() }, t=>[index('idx_responses_activity').on(t.activityId),uniqueIndex('uniq_responses_participant_activity').on(t.participantId,t.activityId)]);

export const reactions = sqliteTable('reactions', { id:text('id').primaryKey(), sessionId:text('session_id').notNull().references(()=>sessions.id), participantId:text('participant_id').notNull().references(()=>participants.id), emoji:text('emoji').notNull(), createdAt:integer('created_at').notNull() }, t=>[index('idx_reactions_session_created').on(t.sessionId,t.createdAt)]);
export const likes = sqliteTable('likes', { postId:text('post_id').notNull().references(()=>posts.id), participantId:text('participant_id').notNull().references(()=>participants.id) }, t=>[index('idx_likes_post').on(t.postId),uniqueIndex('uniq_likes_post_participant').on(t.postId,t.participantId)]);
export const reflections = sqliteTable('reflections', { id:text('id').primaryKey(), sessionId:text('session_id').notNull().references(()=>sessions.id), participantId:text('participant_id').notNull().references(()=>participants.id), takeaway:text('takeaway').notNull(), changed:text('changed').notNull().default(''), createdAt:integer('created_at').notNull() }, t=>[index('idx_reflections_session').on(t.sessionId),uniqueIndex('uniq_reflections_session_participant').on(t.sessionId,t.participantId)]);

export const reports = sqliteTable('reports', { id:text('id').primaryKey(), sessionId:text('session_id').notNull().references(()=>sessions.id), postId:text('post_id').notNull().references(()=>posts.id), participantId:text('participant_id').notNull().references(()=>participants.id), createdAt:integer('created_at').notNull() }, t=>[index('idx_reports_session').on(t.sessionId),uniqueIndex('uniq_reports_post_participant').on(t.postId,t.participantId)]);
